interfaceconfigcreate:
  name:
    required: True
    type: basestring
  project_id:
    required: True
    type: int
  num:
    type: int
  returnvalue:
    - name
    - project_id
    - num


interfaceconfigmodify:
  name:
    required: True
    type: basestring
  project_id:
    required: True
  num:
    type: int
  weight:
    type: int
  returnvalue:
    - name
    - project_id
    - num
    - weight
